name: glossll
description: "Glossed Subtitles for Language Learning."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  google_fonts: ^6.2.1

  provider: ^6.1.2
  http: ^1.2.1
  shared_preferences: ^2.2.3

  package_info_plus: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
